version: '3.8'

services:
  app:
    build:
      context: .
    container_name: secure_laravel_app
    ports:
      - "8001:8001"
    volumes:
      - .:/var/www
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: secure_laravel_db
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: secure_login
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
